# rabbitMQ

## 트러블 슈팅

### 이슈 발생

- GPU 서버의 FASTAPI에서 rabbbitMQ로 메시지 발송 시, rabbitMQ 채널이 닫혀있다는 오류가 발생

### 에러 분석

- 에러 메시지 분석 결과, rabbitMQ와의 연결이 끊어진 게 아니라 채널이 닫혀있는데 메시지를 발송하려고 해서 발송하지 못한다는 에러였음

### 시도

- 기존 코드 분석 결과, 메시지 발송 마다 채널을 재생성하고 큐를 지정하고 있었음

```python
channel = rabbitmq_connection.channel()  # 채널 재생성
channel.queue_declare(queue='hello', durable=True)
```

- 채널을 재생성하는 것이 원인이지 않을까 싶어 해당 코드를 사용하지 않고 전역에 설정된 채널을 이용하여 publish 작업만 하도록 코드를 수정하였음 -> 여전히 똑같은 오류가 발생함

- 채널이 닫혀있으면 채널을 재생성하고 연결하도록 코드를 수정 -> 해결되지 않음

### 인사이트

- 에러 메시지에서 다음과 같은 내용이 눈에 들어왔음.

```
Exception in thread Thread-1625 (_handle_eio_message):
```

- 해당 메시지는 1625번 쓰레드에서 발생하였다는 내용임 -> 쓰레드가 1625개나 된다는게 이상했음

- 각 쓰레드가 동일한 채널을 연결하고 있는거라면 채널 입장에서는 너무 많은 연결에 대응하기 위해 채널을 닫는 것이 맞음

- 웹소켓 메시지 수신 이벤트가 발생할 때 마다 쓰레드를 생성하여 작업하는 것이 default라서 쓰레드가 계속해서 생성되고 있었음

### 두 번째 시도

- 쓰레드를 계속해서 생성하지 않고 재사용하도록 코드를 수정

```python
from concurrent.futures import ThreadPoolExecutor

executor = ThreadPoolExecutor(max_workers=10)

def handle_image(data):
    global rabbitmq_connection, channel
    frame = bytesToImage(data['CCTVImage'])

    message = {"cctv_name": "cctv-1", "speed": 15}
    message_json = json.dumps(message)
    channel.basic_publish(exchange='', routing_key='hello', body=message_json)

@sio.event
def getCCTVImage(data):
    global frame_count
    frame_count += 1
    print(frame_count)
    executor.submit(handle_image, data)
```

- 수정 후 테스트 결과, 오류 발생하지 않음

### 그렇다면, 기존에는 왜 이런 오류가 발생하지 않았는가?

- 기존에는 메시지를 오늘과 같은 양을 보낸 적이 없었음.

- 05.15 첫 번째 테스트 시도 시 오류가 발생하지 않았던 건, 메시지 발송하는 쓰레드가 동일하였거나 다른 이유로 인해 오류가 발생하지 않았던 거 같음.

### 마무리

- rabbitMQ 에러와 별개로 쓰레드를 계속해서 생성하여 작업하는 것 자체가 매우 비효율적이고 낭비적인 작업이므로, 웹소켓으로 매우 많은 task를 처리하는 경우(우리의 경우 초당 10번이나 task를 처리해야 함) 쓰레드를 관리해주는 것이 중요함을 알게 되었음.
